import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/navBar/NavigationBar";
import { cookies } from 'next/headers';
import Providers from "@/context/Providers";
import jwt from "jsonwebtoken";
import { User } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const JWT_SECRET = process.env.JWT_SECRET || "";


const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const cookieStore = await cookies();
  const token = cookieStore.get('token')?.value || "";
  const user = token ? jwt.verify(token, JWT_SECRET) as User : null;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers user={user}>
          <NavigationBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;