import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/navBar/NavigationBar";
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const cookieStore = await cookies();
  const token = cookieStore.get('token')?.value;

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavigationBar isLoggedIn={!!token} />
        {children}</body>
    </html>
  );
}

export default RootLayout;